name: Deploy Bicep file
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      run: |
       az deployment sub create --name demoSubDeployment --template-file .\azure\infra\core\resource group\iac\bicep\code\resourcegroup.bicep --parameters .\azure\infra\core\resource group\iac\bicep\param\resourcegroup.bicepparam