name: Deploy Bicep file
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
   
    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      id: create_rg
      run: |
       RESOURCE_GROUP_NAME=$(az deployment sub create --name demoSubDeployment --location eastus \
       --template-file azure/infra/core/resourcegroup/iac/bicep/code/resourcegroup.bicep \
       --parameters azure/infra/core/resourcegroup/iac/bicep/param/resourcegroup.bicepparam \
       --query 'properties.outputs.resourceGroupName.value' -o tsv)
       echo $RESOURCE_GROUP_NAME
       echo "rg_name=$RESOURCE_GROUP_NAME" >> $GITHUB_OUTPUT

    - name: Save rg group Output
      run: |
            echo "${{ steps.create_rg.outputs.rg_name }}"


    - name: Deploy Linux vm using Bicep file
      id: create_linux_vm
      uses: azure/arm-deploy@v1
      with:
         subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
         resourceGroupName: "${{steps.create_rg.outputs.rg_name}}"
         template: azure/infra/core/VM/LinuxVM/iac/bicep/code/simplelinux.bicep
         parameters: azure/infra/core/VM/LinuxVM/iac/bicep/param/simplelinux.bicepparam
         failOnStdErr: false

    - name: Save Deployment Output
      run: |
           echo "host name: ${{ steps.create_linux_vm.outputs.hostname }}"
           echo "admin user name: ${{ steps.create_linux_vm.outputs.adminUsername }}"

    - name:  scp tomact9 script    
      run: scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} azure/infra/core/VM/LinuxVM/iac/bicep/scripts/tomcat9_insatll.sh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/tomcat9_install.sh
      env:
       SSH_PORT: 22
       SSH_USERNAME: ${{ steps.create_linux_vm.outputs.adminUsername }}
       SSH_HOST: ${{ steps.create_linux_vm.outputs.hostname }}
       SSH_KEY: ${{ secrets.SERVER_PASSWORD }}


     
    - name: SSH into Linux server and run script
      uses: appleboy/ssh-action@master
      with:
              host: ${{ steps.create_linux_vm.outputs.hostname }}
              username: ${{ steps.create_linux_vm.outputs.adminUsername }}
              password: ${{ secrets.SERVER_PASSWORD }}
              port: 22 # Default SSH port is 22
              script: |
               # Change directory to where your script is located
               cd /home/arpan
               #make tomcat9 executable 
               chmod +x tomcat9_insatll.sh
               # Run your script
               ./tomcat9_insatll.sh
    
    - name: Save Deployment Output
      run: |
        echo "tmocat9 url: http://${{ steps.create_linux_vm.outputs.hostname }}:8080"