name: Deploy Bicep file
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy resourcegroup using Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        template: .\azure\infra\core\resource group\iac\bicep\code\resourcegroup.bicep
        parameters: .\azure\infra\core\resource group\iac\bicep\param\resourcegroup.bicepparam
        failOnStdErr: false